/**
 * Seed Data - All 6 editions from the mobile app (source of truth)
 * Used by the "Importer" button on the editions page to populate Firestore.
 */

export const SEED_EDITIONS = [
  {
    id: "classic",
    name: "Édition Classique",
    description: "L'édition de base avec des questions générales sur l'entrepreneuriat",
    icon: "briefcase-outline",
    color: "#FFBC40",
    quizzes: [],
    duels: [],
    fundings: [],
    opportunities: [],
    challenges: [],
    startupIdeas: [],
  },
  {
    id: "agriculture",
    name: "Édition Agriculture",
    description: "Spécialisée dans l'AgriTech et l'agriculture durable",
    icon: "leaf-outline",
    color: "#4CAF50",
    quizzes: [],
    duels: [],
    fundings: [],
    opportunities: [],
    challenges: [],
    startupIdeas: [],
  },
  {
    id: "education",
    name: "Édition Éducation",
    description: "Focalisée sur l'EdTech et les innovations éducatives",
    icon: "school-outline",
    color: "#2196F3",
    quizzes: [],
    duels: [],
    fundings: [],
    opportunities: [],
    challenges: [],
    startupIdeas: [],
  },
  {
    id: "sante",
    name: "Édition Santé & Bien-être",
    description: "Dédiée à la HealthTech et aux innovations médicales",
    icon: "medkit-outline",
    color: "#F44336",
    quizzes: [
      { id: "quiz_1", question: "Quelle mesure est la plus efficace pour prévenir les infections nosocomiales ?", options: ["La ventilation intensive des locaux", "L'hygiène des mains systématique", "La désinfection quotidienne des sols"], correctAnswer: 1, category: "Aspects techniques médicaux" },
      { id: "quiz_2", question: "Quel est le principal avantage de la télémédecine pour les patients en zone rurale ?", options: ["Des consultations toujours moins chères", "L'accès à des spécialistes distants", "L'absence totale de déplacement"], correctAnswer: 1, category: "Aspects techniques médicaux" },
      { id: "quiz_3", question: "Quelle approche diagnostique est considérée comme la plus fiable ?", options: ["Le diagnostic basé sur l'expérience seule", "L'utilisation exclusive des examens complémentaires", "L'approche clinique combinée aux examens pertinents"], correctAnswer: 2, category: "Aspects techniques médicaux" },
      { id: "quiz_4", question: "Quelle stratégie de prévention a le meilleur rapport coût-efficacité ?", options: ["Les campagnes de vaccination", "Les dépistages systématiques coûteux", "Les traitements précoces uniquement"], correctAnswer: 0, category: "Aspects techniques médicaux" },
      { id: "quiz_5", question: "Quel est l'avantage principal des médicaments génériques ?", options: ["Ils sont toujours plus efficaces", "Ils réduisent les coûts sans compromettre l'efficacité", "Ils ont moins d'effets secondaires"], correctAnswer: 1, category: "Aspects techniques médicaux" },
    ],
    duels: [
      { id: "duel_1", question: "Quelle mesure est la plus efficace pour prévenir les infections nosocomiales dans un centre de santé?", options: [{ text: "L'hygiène des mains systématique du personnel", points: 30 }, { text: "La désinfection quotidienne des sols", points: 20 }, { text: "La ventilation intensive des locaux", points: 10 }], category: "santé" },
      { id: "duel_2", question: "Quel est le principal avantage de la télémédecine pour les zones rurales africaines?", options: [{ text: "Réduire les coûts de déplacement", points: 20 }, { text: "L'accès à des spécialistes distants sans déplacement", points: 30 }, { text: "Automatiser les prescriptions médicales", points: 10 }], category: "tech" },
      { id: "duel_3", question: "Comment convaincre un investisseur de financer une startup HealthTech?", options: [{ text: "Montrer un business plan détaillé sur 10 ans", points: 10 }, { text: "Présenter des métriques d'impact et de traction", points: 30 }, { text: "Mettre en avant les diplômes de l'équipe", points: 20 }], category: "pitch" },
      { id: "duel_4", question: "Quelle stratégie de pricing est la plus adaptée pour un service de santé en Afrique?", options: [{ text: "Un modèle freemium avec consultations de base gratuites", points: 20 }, { text: "Des tarifs ajustés au pouvoir d'achat local avec mobile money", points: 30 }, { text: "S'aligner sur les prix des cliniques privées existantes", points: 10 }], category: "pricing" },
    ],
    fundings: [
      { id: "fin_1", title: "Tontine santé communautaire", description: "Système d'épargne rotatif pour projets santé.", tokens: 3 },
      { id: "fin_2", title: "Microcrédit médical", description: "Petit prêt adapté aux revenus médicaux.", tokens: 4 },
      { id: "fin_3", title: "Prêt bancaire santé", description: "Financement bancaire pour investissements médicaux.", tokens: 5 },
      { id: "fin_4", title: "Subvention publique ou fondation", description: "Financement non remboursable pour projets santé.", tokens: 4 },
      { id: "fin_5", title: "Investisseur HealthTech", description: "Investisseur en technologies de santé.", tokens: 5 },
      { id: "fin_6", title: "Financement participatif santé", description: "Campagne de financement collaboratif santé.", tokens: 3 },
    ],
    opportunities: [
      { id: "opp_1", title: "Partenariat avec une mutuelle de santé", description: "Vous signez un accord avec une mutuelle locale. Gagnez 3 jetons.", tokens: 3 },
      { id: "opp_2", title: "Certification qualité obtenue", description: "Certification ISO ou HAS obtenue. Gagnez 3 jetons.", tokens: 3 },
      { id: "opp_3", title: "Télémédecine développée", description: "Plateforme de téléconsultation lancée. Gagnez 3 jetons.", tokens: 3 },
      { id: "opp_4", title: "Équipement médical innovant", description: "Investissement dans une technologie de pointe. Gagnez 3 jetons.", tokens: 3 },
      { id: "opp_5", title: "Formation spécialisée réussie", description: "Spécialisation obtenue. Gagnez 2 jetons.", tokens: 2 },
      { id: "opp_6", title: "Centre de bien-être intégré", description: "Espace holistique créé. Gagnez 3 jetons.", tokens: 3 },
      { id: "opp_7", title: "Réseau de praticiens constitué", description: "Équipe pluridisciplinaire fédérée. Gagnez 2 jetons.", tokens: 2 },
      { id: "opp_8", title: "Application santé lancée", description: "App de santé lancée avec succès. Gagnez 3 jetons.", tokens: 3 },
      { id: "opp_9", title: "Partenariat avec entreprises", description: "Contrats de médecine du travail signés. Gagnez 3 jetons.", tokens: 3 },
      { id: "opp_10", title: "Centre de recherche clinique", description: "Participation à des essais cliniques. Gagnez 3 jetons.", tokens: 3 },
      { id: "opp_11", title: "Programme HealthTech Accelerator", description: "Accélérateur en technologies de santé intégré. Gagnez 3 jetons.", tokens: 3 },
      { id: "opp_12", title: "Programme Digital Health", description: "Formation en santé numérique. Gagnez 2 jetons.", tokens: 2 },
      { id: "opp_13", title: "Programme Silver Economy", description: "Programme dédié aux seniors. Gagnez 3 jetons.", tokens: 3 },
      { id: "opp_14", title: "Programme Wellness Innovation", description: "Innovation en bien-être. Gagnez 2 jetons.", tokens: 2 },
      { id: "opp_15", title: "Programme MedTech Cluster", description: "Cluster technologique médical intégré. Gagnez 3 jetons.", tokens: 3 },
    ],
    challenges: [
      { id: "chal_1", title: "Épidémie locale", description: "Restrictions sanitaires. Perdez 3 jetons.", tokens: -3 },
      { id: "chal_2", title: "Pénurie de médicaments", description: "Rupture d'approvisionnement. Perdez 2 jetons.", tokens: -2 },
      { id: "chal_3", title: "Changement de réglementation", description: "Nouveaux remboursements défavorables. Perdez 2 jetons.", tokens: -2 },
      { id: "chal_4", title: "Problème d'assurance", description: "Assurance résiliée. Payez 2 jetons.", tokens: -2 },
      { id: "chal_5", title: "Panne d'équipement critique", description: "Matériel en panne. Perdez 2 jetons.", tokens: -2 },
      { id: "chal_6", title: "Refus de financement", description: "Prêt refusé. Perdez 2 jetons.", tokens: -2 },
      { id: "chal_7", title: "Cyberattaque", description: "Ransomware sur vos systèmes. Perdez 3 jetons.", tokens: -3 },
      { id: "chal_8", title: "Problème de stérilisation", description: "Fermeture temporaire. Perdez 2 jetons.", tokens: -2 },
      { id: "chal_9", title: "Inspection sanitaire négative", description: "Non-conformités détectées. Perdez 2 jetons.", tokens: -2 },
      { id: "chal_10", title: "Retards de remboursement", description: "Problèmes de trésorerie. Perdez 2 jetons.", tokens: -2 },
    ],
    startupIdeas: [],
  },
  {
    id: "tourisme",
    name: "Édition Tourisme",
    description: "Axée sur la TravelTech et l'hospitalité",
    icon: "airplane-outline",
    color: "#FF9800",
    quizzes: [],
    duels: [],
    fundings: [],
    opportunities: [],
    challenges: [],
    startupIdeas: [],
  },
  {
    id: "culture",
    name: "Édition Culture",
    description: "Centrée sur les industries créatives et culturelles",
    icon: "color-palette-outline",
    color: "#9C27B0",
    quizzes: [],
    duels: [],
    fundings: [],
    opportunities: [],
    challenges: [],
    startupIdeas: [],
  },
];
